name: build

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
			with:
				node-version: '17.x'
            - name: Build web-app
			run: |
				yarn ci
				yarn build
            - name: Deploy to ecommerce/
			uses: peaceiris/actions-gh-pages@v3
			with:
				github_token: ${{ secrets.GITHUB_TOKEN }}
				publish_dir ./build
